name: Node Project CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: npm install --prefix nasa-5
      - run: npm run build-client --prefix nasa-5